version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: rluisr
    password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
updates:
  - package-ecosystem: gomod
    directory: "/"
    registries:
      - github-octocat
    target-branch: "staging"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "github.com/sendgrid/sendgrid-go"
