FROM oraclelinux:7-slim

ARG MYSQL_YUM_REPO_URL

RUN yum install -y $MYSQL_YUM_REPO_URL \
    && yum-config-manager --enable mysql-innovation-community \
    && yum install -y mysql-community-client mysql-router-community libpwquality \
    && yum clean all

COPY mysqlrouter.pwd /mysqlrouter.pwd
COPY run_http.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh

HEALTHCHECK \
	CMD mysqladmin --port 6446 --protocol TCP ping 2>&1 | grep Access || exit 1

EXPOSE 8080
ENTRYPOINT ["/tmp/run.sh"]
CMD ["mysqlrouter"]