FROM oraclelinux:7-slim

RUN rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022 \
    && yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-8.noarch.rpm \
    && yum install -y mysql-community-client mysql-router-community libpwquality \
    && yum clean all

COPY mysqlrouter.pwd /mysqlrouter.pwd
COPY run_http.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh

HEALTHCHECK \
	CMD mysqladmin --port 6446 --protocol TCP ping 2>&1 | grep Access || exit 1

EXPOSE 8080
ENTRYPOINT ["/tmp/run.sh"]
CMD ["mysqlrouter"]